#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
#include <wchar.h>
#include <iostream>
#include <time.h>
#include <fstream>
#include <mbstring.h>
#include <iomanip>
#include <cstring>
#include <ctime>
#include <cstdlib>
#include <stack>
#include <queue>
#include <string>
#include <sstream>
